In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
hollywood_df = pd.read_csv('Datasets/modified_hollywood_movies.csv') #loading the both modified datasets
indian_df = pd.read_csv('Datasets/modified_indian_movies.csv')

In [16]:
final_movies_df = pd.concat([hollywood_df, indian_df], axis=0).reset_index(drop=True) #merging the datasets
final_movies_df

,Name,Year,Genre,Budget,Duration,Rating,Language,Industry
0,The Blue Lagoon,1980.0,Adventure,4500000,104,5.8,English,Hollywood
1,Star Wars: Episode V - The Empire Strikes Back,1980.0,Action,18000000,124,8.7,English,Hollywood
2,Airplane!,1980.0,Comedy,3500000,88,7.7,English,Hollywood
3,Caddyshack,1980.0,Comedy,6000000,98,7.3,English,Hollywood
4,Friday the 13th,1980.0,Horror,550000,95,6.4,English,Hollywood
...,...,...,...,...,...,...,...,...
9155,Karthavyam,1990.0,"Action ,Drama",1400000,145,7.0,Telugu,Tollywood
9156,Commissioner,1994.0,"Action ,Crime ,Thriller",1400000,175,7.5,Malayalam,Mollywood
9157,Seetharamaiah Gari Manavaralu,1991.0,Drama,1400000,145,7.7,Telugu,Tollywood
9158,Muqaddar,1996.0,Crime,1400000,140,6.2,Hindi,Bollywood
9159,Enga Muthalali,1993.0,Drama,1400000,150,6.2,Tamil,Kollywood

In [17]:
final_movies_df[final_movies_df.duplicated()] #checking for duplicate rows after merging

,Name,Year,Genre,Budget,Duration,Rating,Language,Industry
7520,Vanity Fair,2004.0,Drama,23000000,141,6.2,English,Hollywood

In [18]:
final_movies_df[final_movies_df.duplicated(subset=['Name'])] #checking for duplicate movie names after merging

,Name,Year,Genre,Budget,Duration,Rating,Language,Industry
5386,Action Jackson,2014.0,"Action ,Thriller",13020000,144,3.2,Hindi,Bollywood
5432,Cocktail,2012.0,"Comedy ,Drama ,Romance",7980000,146,6.3,Hindi,Bollywood
5463,Commando,2013.0,"Action ,Thriller",1400000,124,6.1,Hindi,Bollywood
5551,One Night Stand,2016.0,"Drama ,Romance",1400000,97,3.1,Hindi,Bollywood
5569,Chef,2017.0,"Comedy ,Drama ,Family",1400000,133,5.7,Hindi,Bollywood
...,...,...,...,...,...,...,...,...
8217,Frozen,2007.0,Drama,1400000,109,7.1,Hindi,Bollywood
8472,Criminal,1995.0,"Action ,Romance ,Thriller",1400000,123,5.7,Hindi,Bollywood
8604,Soldier,1998.0,"Musical ,Mystery ,Action ,Drama ,Romance ,Thri...",1400000,156,6.1,Hindi,Bollywood
8886,Honeymoon,1992.0,"Comedy ,Drama",1400000,160,5.8,Hindi,Bollywood
8922,Cheetah,1994.0,"Action ,Drama",1400000,140,6.1,Hindi,Bollywood

In [19]:
final_movies_df[final_movies_df.duplicated(subset=['Name','Year','Language'])].shape #checking for duplicate movie names along with year and language

(28, 8)

In [20]:
final_movies_df.drop_duplicates(subset=['Name','Year','Language'], keep='first', inplace=True) #dropping duplicate movie names along with year and language

In [21]:
final_movies_df.reset_index(drop=True, inplace=True)
final_movies_df

,Name,Year,Genre,Budget,Duration,Rating,Language,Industry
0,The Blue Lagoon,1980.0,Adventure,4500000,104,5.8,English,Hollywood
1,Star Wars: Episode V - The Empire Strikes Back,1980.0,Action,18000000,124,8.7,English,Hollywood
2,Airplane!,1980.0,Comedy,3500000,88,7.7,English,Hollywood
3,Caddyshack,1980.0,Comedy,6000000,98,7.3,English,Hollywood
4,Friday the 13th,1980.0,Horror,550000,95,6.4,English,Hollywood
...,...,...,...,...,...,...,...,...
9127,Karthavyam,1990.0,"Action ,Drama",1400000,145,7.0,Telugu,Tollywood
9128,Commissioner,1994.0,"Action ,Crime ,Thriller",1400000,175,7.5,Malayalam,Mollywood
9129,Seetharamaiah Gari Manavaralu,1991.0,Drama,1400000,145,7.7,Telugu,Tollywood
9130,Muqaddar,1996.0,Crime,1400000,140,6.2,Hindi,Bollywood
9131,Enga Muthalali,1993.0,Drama,1400000,150,6.2,Tamil,Kollywood

In [22]:
final_movies_df.duplicated().any() #rechecking for duplicate rows

False

In [23]:
final_movies_df = final_movies_df.sort_values(by='Year', ascending= True).reset_index(drop=True)
final_movies_df

,Name,Year,Genre,Budget,Duration,Rating,Language,Industry
0,The Blue Lagoon,1980.0,Adventure,4500000,104,5.8,English,Hollywood
1,Resurrection,1980.0,Drama,37010639,103,7.3,English,Hollywood
2,Honeysuckle Rose,1980.0,Drama,37010639,119,6.3,English,Hollywood
3,It's My Turn,1980.0,Comedy,37010639,91,5.5,English,Hollywood
4,The Competition,1980.0,Drama,37010639,123,6.7,English,Hollywood
...,...,...,...,...,...,...,...,...
9127,Onward,2020.0,Animation,37010639,102,7.4,English,Hollywood
9128,Wonder Woman 1984,2020.0,Action,37010639,151,5.4,English,Hollywood
9129,Tenet,2020.0,Action,205000000,150,7.4,English,Hollywood
9130,Dolittle,2020.0,Adventure,175000000,101,5.6,English,Hollywood
9131,Dream Round,2020.0,Comedy,37010639,90,4.7,English,Hollywood

In [24]:
final_movies_df['Year'] = final_movies_df['Year'].astype('Int64') #converting year column to integer type

In [25]:
final_movies_df.dtypes

Name         object
Year          Int64
Genre        object
Budget        int64
Duration      int64
Rating      float64
Language     object
Industry     object
dtype: object

In [26]:
final_movies_df.to_csv('Datasets/final_movies_dataset.csv', index=False) #saving the final merged dataset for visualization and analysis